export { default as earth } from "assets/images/icons/earth.png";
export { default as furnace } from "assets/images/icons/furnace.png";
export { default as ice } from "assets/images/icons/ice.png";
export { default as tool } from "assets/images/icons/tool.png";
export { default as animal } from "assets/images/icons/animal.png";
export { default as bacteria } from "assets/images/icons/bacteria.png";
export { default as egg } from "assets/images/icons/egg.png";
export { default as meat } from "assets/images/icons/meat.png";
export { default as milk } from "assets/images/icons/milk.png";
export { default as kefir } from "assets/images/icons/kefir.png";
export { default as cream } from "assets/images/icons/cream.png";
export { default as cheese } from "assets/images/icons/cheese.png";
export { default as bluecheese } from "assets/images/icons/blue cheese.png";
export { default as water } from "assets/images/icons/water.png";
export { default as boilingwater } from "assets/images/icons/boiling water.png";
export { default as seed } from "assets/images/icons/seed.png";
export { default as popcorn } from "assets/images/icons/popcorn.png";
export { default as forcemeat } from "assets/images/icons/forcemeat.png";
export { default as kebab } from "assets/images/icons/kebab.png";
export { default as omelette } from "assets/images/icons/omelette.png";
export { default as fish } from "assets/images/icons/fish.png";
export { default as boiledegg } from "assets/images/icons/boiled egg.png";
export { default as roast } from "assets/images/icons/roast.png";
export { default as condensedmilk } from "assets/images/icons/condensed milk.png";
export { default as burnedsomething } from "assets/images/icons/burned something.png";
export { default as sausage } from "assets/images/icons/sausage.png";
export { default as grass } from "assets/images/icons/grass.png";
export { default as fishsoup } from "assets/images/icons/fish soup.png";
export { default as tea } from "assets/images/icons/tea.png";
export { default as cutlet } from "assets/images/icons/cutlet.png";
export { default as koumiss } from "assets/images/icons/koumiss.png";
export { default as fondue } from "assets/images/icons/fondue.png";
export { default as friedfish } from "assets/images/icons/fried fish.png";
export { default as cereal } from "assets/images/icons/cereal.png";
export { default as manure } from "assets/images/icons/manure.png";
export { default as spices } from "assets/images/icons/spices.png";
export { default as surströmming } from "assets/images/icons/surströmming.png";
export { default as bush } from "assets/images/icons/bush.png";
export { default as flower } from "assets/images/icons/flower.png";
export { default as mojito } from "assets/images/icons/mojito.png";
export { default as iceTea } from "assets/images/icons/ice tea.png";
export { default as flour } from "assets/images/icons/flour.png";
export { default as kvass } from "assets/images/icons/kvass.png";
export { default as porridge } from "assets/images/icons/porridge.png";
export { default as berry } from "assets/images/icons/berry.png";
export { default as sauce } from "assets/images/icons/sauce.png";
export { default as tree } from "assets/images/icons/tree.png";
export { default as nut } from "assets/images/icons/nut.png";
export { default as honey } from "assets/images/icons/honey.png";
export { default as dough } from "assets/images/icons/dough.png";
export { default as beer } from "assets/images/icons/beer.png";
export { default as pilaf } from "assets/images/icons/pilaf.png";
export { default as sushi } from "assets/images/icons/sushi.png";
export { default as juice } from "assets/images/icons/juice.png";
export { default as jam } from "assets/images/icons/jam.png";
export { default as wine } from "assets/images/icons/wine.png";
export { default as yogurt } from "assets/images/icons/yogurt.png";
export { default as mayonnaise } from "assets/images/icons/mayonnaise.png";
export { default as coffeebean } from "assets/images/icons/coffee bean.png";
export { default as cocoabean } from "assets/images/icons/cocoa bean.png";
export { default as fruit } from "assets/images/icons/fruit.png";
export { default as reed } from "assets/images/icons/reed.png";
export { default as sugar } from "assets/images/icons/sugar.png";
export { default as caramel } from "assets/images/icons/caramel.png";
export { default as syrup } from "assets/images/icons/syrup.png";
export { default as eggnog } from "assets/images/icons/eggnog.png";
export { default as butterdough } from "assets/images/icons/butter dough.png";
export { default as milkshake } from "assets/images/icons/milkshake.png";
export { default as icecream } from "assets/images/icons/ice cream.png";
export { default as candy } from "assets/images/icons/candy.png";
export { default as cottoncandy } from "assets/images/icons/cotton candy.png";
export { default as cremebrulee } from "assets/images/icons/creme brulee.png";
export { default as croissant } from "assets/images/icons/croissant.png";
export { default as nutbutter } from "assets/images/icons/nut butter.png";
export { default as muesli } from "assets/images/icons/muesli.png";
export { default as gozinaki } from "assets/images/icons/gozinaki.png";
export { default as mead } from "assets/images/icons/mead.png";
export { default as cookie } from "assets/images/icons/cookie.png";
export { default as gingerbread } from "assets/images/icons/gingerbread.png";
export { default as toffee } from "assets/images/icons/toffee.png";
export { default as baklava } from "assets/images/icons/baklava.png";
export { default as pie } from "assets/images/icons/pie.png";
export { default as cake } from "assets/images/icons/cake.png";
export { default as marshmallow } from "assets/images/icons/marshmallow.png";
export { default as mustard } from "assets/images/icons/mustard.png";
export { default as topping } from "assets/images/icons/topping.png";
