import { Element, FoodType } from "./types";

export const startElements: Element[] = [
  Element.Animal,
  Element.Earth,
  Element.Furnace,
  Element.Ice,
  Element.Tool,
];

export const foodTypesMap: Record<Element, FoodType> = {
  [Element.Burned_Something]: FoodType.Inedible,
  [Element.Reed]: FoodType.Plant,
  [Element.Fish_Soup]: FoodType.Animal,
  [Element.Koumiss]: FoodType.Milk,
  [Element.Surstromming]: FoodType.Animal,
  [Element.Bush]: FoodType.Plant,
  [Element.Cotton_Candy]: FoodType.Sweet,
  [Element.Eggnog]: FoodType.Sweet,
  [Element.Ice_Tea]: FoodType.Drink,
  [Element.Kvass]: FoodType.Drink,
  [Element.Sushi]: FoodType.Animal,
  [Element.Baklava]: FoodType.Sweet,
  [Element.Pilaf]: FoodType.Meat,
  [Element.Muesli]: FoodType.Vegan,
  [Element.Gozinaki]: FoodType.Sweet,
  [Element.Mead]: FoodType.Drink,
  [Element.Gingerbread]: FoodType.Bakery,
  [Element.Manure]: FoodType.Inedible,
  [Element.Tree]: FoodType.Plant,
  [Element.Fondue]: FoodType.Milk,
  [Element.Creme_Brulee]: FoodType.Sweet,
  [Element.Croissant]: FoodType.Bakery,
  [Element.Hot_Dog]: FoodType.Fastfood,
  [Element.Hamburger]: FoodType.Fastfood,
  [Element.Popcorn]: FoodType.Fastfood,
  [Element.Communion]: FoodType.Other,
  [Element.Beer]: FoodType.Drink,
  [Element.Vodka]: FoodType.Drink,
  [Element.Brandy]: FoodType.Drink,
  [Element.Liqueur]: FoodType.Drink,
  [Element.Cider]: FoodType.Drink,
  [Element.Soda]: FoodType.Drink,
  [Element.Cola]: FoodType.Drink,
  [Element.Mulled_Wine]: FoodType.Drink,
  [Element.Ground_Coffee]: FoodType.Other,
  [Element.Cocoa_Powder]: FoodType.Other,
  [Element.Cocoa_Bean]: FoodType.Plant,
  [Element.Coffee_Bean]: FoodType.Plant,
  [Element.Shawerma]: FoodType.Fastfood,
  [Element.Animal]: FoodType.Animal,
  [Element.Earth]: FoodType.Inedible,
  [Element.Furnace]: FoodType.Inedible,
  [Element.Ice]: FoodType.Other,
  [Element.Tool]: FoodType.Inedible,
  [Element.Bacteria]: FoodType.Animal,
  [Element.Egg]: FoodType.Animal,
  [Element.Meat]: FoodType.Meat,
  [Element.Milk]: FoodType.Milk,
  [Element.Water]: FoodType.Drink,
  [Element.Boiling_Water]: FoodType.Drink,
  [Element.Omelette]: FoodType.Animal,
  [Element.Kebab]: FoodType.Fastfood,
  [Element.Forcemeat]: FoodType.Meat,
  [Element.Kefir]: FoodType.Milk,
  [Element.Cream]: FoodType.Milk,
  [Element.Cheese]: FoodType.Milk,
  [Element.Blue_Cheese]: FoodType.Milk,
  [Element.Boiled_Egg]: FoodType.Animal,
  [Element.Roast]: FoodType.Meat,
  [Element.Condensed_Milk]: FoodType.Milk,
  [Element.Milkshake]: FoodType.Drink,
  [Element.Fish]: FoodType.Animal,
  [Element.Seed]: FoodType.Plant,
  [Element.Grass]: FoodType.Plant,
  [Element.Sugar]: FoodType.Other,
  [Element.Sausage]: FoodType.Meat,
  [Element.Tea]: FoodType.Drink,
  [Element.Cutlet]: FoodType.Meat,
  [Element.Toffee]: FoodType.Sweet,
  [Element.Ice_Cream]: FoodType.Sweet,
  [Element.Fried_Fish]: FoodType.Animal,
  [Element.Cereal]: FoodType.Plant,
  [Element.Mojito]: FoodType.Drink,
  [Element.Spices]: FoodType.Other,
  [Element.Flower]: FoodType.Plant,
  [Element.Caramel]: FoodType.Sweet,
  [Element.Syrup]: FoodType.Sweet,
  [Element.Butter_Dough]: FoodType.Bakery,
  [Element.Flour]: FoodType.Other,
  [Element.Porridge]: FoodType.Vegan,
  [Element.Berry]: FoodType.Vegan,
  [Element.Sauce]: FoodType.Other,
  [Element.Nut]: FoodType.Vegan,
  [Element.Honey]: FoodType.Animal,
  [Element.Candy]: FoodType.Sweet,
  [Element.Cookie]: FoodType.Bakery,
  [Element.Pie]: FoodType.Bakery,
  [Element.Cake]: FoodType.Bakery,
  [Element.Dough]: FoodType.Bakery,
  [Element.Juice]: FoodType.Drink,
  [Element.Wine]: FoodType.Drink,
  [Element.Jam]: FoodType.Sweet,
  [Element.Yogurt]: FoodType.Milk,
  [Element.Marshmallow]: FoodType.Sweet,
  [Element.Mayonnaise]: FoodType.Other,
  [Element.Fruit]: FoodType.Vegan,
  [Element.Nut_Butter]: FoodType.Other,
  [Element.Mustard]: FoodType.Other,
  [Element.Topping]: FoodType.Other,
  [Element.Bread]: FoodType.Bakery,
  [Element.Pita]: FoodType.Bakery,
  [Element.Baozi]: FoodType.Bakery,
  [Element.Spaghetti]: FoodType.Bakery,
  [Element.Noodles]: FoodType.Bakery,
  [Element.Alcohol]: FoodType.Drink,
  [Element.Cocoa]: FoodType.Drink,
  [Element.Chocolate]: FoodType.Sweet,
  [Element.Coffee]: FoodType.Drink,
  [Element.Latte]: FoodType.Drink,
  [Element.Vegetable]: FoodType.Vegan,
  [Element.Toast]: FoodType.Bakery,
  [Element.Sandwich]: FoodType.Fastfood,
  [Element.Hot_Chocolate]: FoodType.Drink,
  [Element.Eskimo]: FoodType.Sweet,
  [Element.Chocolate_Bar]: FoodType.Sweet,
  [Element.Muffin]: FoodType.Bakery,
  [Element.French_Fries]: FoodType.Fastfood,
  [Element.Salad]: FoodType.Vegan,
  [Element.Soup]: FoodType.Vegan,
  [Element.Ketchup]: FoodType.Other,
};

export const elementsLength = Object.keys(foodTypesMap).length;
