export type FoodType =
  | "animal"
  | "bakery"
  | "drink"
  | "meat"
  | "milk"
  | "other"
  | "plant"
  | "inedible"
  | "fastfood"
  | "vegan"
  | "sweet";

export type ElementType = typeof elementsList[number];

export type ElementEntriesType = [ElementType, FoodType];

type ElementsType = { [key in ElementType]: FoodType };

type RecipesType = [[ElementType, ElementType], ElementType | ElementType[]][];

export type RecipesByElementType = {
  [key in ElementType]?: {
    [key in ElementType]?: ElementType | ElementType[];
  };
};

export const startElements: ElementType[] = [
  "animal",
  "earth",
  "furnace",
  "ice",
  "tool",
];

export const elementsList = [
  "animal",
  "earth",
  "furnace",
  "ice",
  "tool",
  "bacteria",
  "egg",
  "meat",
  "milk",
  "arable",
  "water",
  "boiling water",
  "omelette",
  "kebab",
  "burned something",
  "forcemeat",
  "kefir",
  "cream",
  "cheese",
  "blue cheese",
  "boiled egg",
  "roast",
  "condensed milk",
  "milkshake",
  "fish",
  "seed",
  "grass",
  "reed",
  "sugar",
  "sausage",
  "fish soup",
  "tea",
  "cutlet",
  "koumiss",
  "fondue",
  "ice cream",
  "fried fish",
  "surströmming",
  "popcorn",
  "cereal",
  "manure",
  "mojito",
  "spices",
  "bush",
  "flower",
  "caramel",
  "cotton candy",
  "eggnog",
  "syrup",
  "butter dough",
  "ice tea",
  "flour",
  "kvass",
  "porridge",
  "sushi",
  "berry",
  "sauce",
  "tree",
  "nut",
  "honey",
  "candy",
  "creme brulee",
  "bun",
  "cookie",
  "dough",
  "beer",
  "pilaf",
  "juice",
  "wine",
  "jam",
  "yogurt",
  "mayonnaise",
  "cocoa bean",
  "coffee bean",
  "fruit",
  "nut butter",
  "muesli",
  "gozinaki",
  "mead",
  "gingerbread",
] as const;

export const allElements: ElementsType = {
  animal: "animal",
  earth: "inedible",
  furnace: "inedible",
  ice: "other",
  tool: "inedible",
  bacteria: "animal",
  egg: "animal",
  meat: "meat",
  milk: "milk",
  arable: "inedible",
  water: "drink",
  "boiling water": "drink",
  omelette: "animal",
  kebab: "meat",
  "burned something": "inedible",
  forcemeat: "meat",
  kefir: "milk",
  cream: "milk",
  cheese: "milk",
  "blue cheese": "milk",
  "boiled egg": "animal",
  roast: "meat",
  "condensed milk": "milk",
  milkshake: "drink",
  fish: "animal",
  seed: "plant",
  reed: "plant",
  grass: "plant",
  sugar: "other",
  sausage: "meat",
  "fish soup": "animal",
  tea: "drink",
  cutlet: "meat",
  koumiss: "milk",
  fondue: "milk",
  "ice cream": "sweet",
  "fried fish": "animal",
  surströmming: "animal",
  popcorn: "fastfood",
  cereal: "plant",
  manure: "inedible",
  mojito: "drink",
  spices: "other",
  bush: "plant",
  flower: "plant",
  caramel: "sweet",
  "cotton candy": "sweet",
  eggnog: "sweet",
  syrup: "sweet",
  "butter dough": "bakery",
  "ice tea": "drink",
  flour: "other",
  kvass: "drink",
  porridge: "vegan",
  sushi: "animal",
  berry: "vegan",
  sauce: "other",
  tree: "plant",
  nut: "vegan",
  honey: "animal",
  candy: "sweet",
  "creme brulee": "sweet",
  bun: "bakery",
  cookie: "bakery",
  dough: "bakery",
  beer: "drink",
  pilaf: "meat",
  juice: "drink",
  wine: "drink",
  jam: "sweet",
  yogurt: "milk",
  mayonnaise: "other",
  "cocoa bean": "plant",
  "coffee bean": "plant",
  fruit: "vegan",
  "nut butter": "other",
  muesli: "vegan",
  gozinaki: "sweet",
  mead: "drink",
  gingerbread: "bakery",
};

// todo burned something for all
const recipes: RecipesType = [
  [["animal", "earth"], "bacteria"],
  [
    ["animal", "tool"],
    ["egg", "meat", "milk"],
  ],
  [["earth", "tool"], "arable"],
  [["furnace", "ice"], "water"],
  [["furnace", "water"], "boiling water"],
  [["egg", "furnace"], "omelette"],
  [["furnace", "meat"], "kebab"],
  [["furnace", "omelette"], "burned something"],
  [["furnace", "kebab"], "burned something"],
  [["furnace", "cream"], "burned something"],
  [["furnace", "boiled egg"], "burned something"],
  [["furnace", "blue cheese"], "burned something"],
  [["furnace", "roast"], "burned something"],
  [["furnace", "condensed milk"], "burned something"],
  [["tool", "meat"], "forcemeat"],
  [["bacteria", "milk"], "kefir"],
  [["bacteria", "kefir"], "cream"],
  [["bacteria", "cream"], "cheese"],
  [["bacteria", "cheese"], "blue cheese"],
  [["boiling water", "egg"], "boiled egg"],
  [["boiling water", "meat"], "roast"],
  [["furnace", "milk"], "condensed milk"],
  [["milk", "tool"], "milkshake"],
  [["animal", "water"], "fish"],
  [["earth", "water"], "seed"],
  [["seed", "water"], "reed"],
  [["earth", "seed"], "grass"],
  [["boiling water", "forcemeat"], "sausage"],
  [["boiling water", "fish"], "fish soup"],
  [["boiling water", "grass"], "tea"],
  [["forcemeat", "furnace"], "cutlet"],
  [["kefir", "tool"], "koumiss"],
  [["cheese", "furnace"], "fondue"],
  [["ice", "milkshake"], "ice cream"],
  [["fish", "furnace"], "fried fish"],
  [["bacteria", "fish"], "surströmming"],
  [["grass", "seed"], "cereal"],
  [["reed", "tool"], "sugar"],
  [["cereal", "furnace"], "popcorn"],
  [["animal", "grass"], "manure"],
  [["grass", "ice"], "mojito"],
  [["grass", "tool"], "spices"],
  [["grass", "water"], "bush"],
  [["grass", "manure"], "flower"],
  [["furnace", "sugar"], "caramel"],
  [["tool", "sugar"], "cotton candy"],
  [["egg", "sugar"], "eggnog"],
  [["sugar", "water"], "syrup"],
  [["dough", "sugar"], "butter dough"],
  [["ice", "tea"], "ice tea"],
  [["cereal", "tool"], "flour"],
  [["bacteria", "cereal"], "kvass"],
  [["boiling water", "cereal"], "porridge"],
  [["cereal", "fish"], "sushi"],
  [["bush", "manure"], "berry"],
  [["spices", "water"], "sauce"],
  [["bush", "water"], "tree"],
  [["bush", "seed"], "nut"],
  [["animal", "flower"], "honey"],
  [["caramel", "ice"], "candy"],
  [["caramel", "condensed milk"], "creme brulee"],
  [
    ["butter dough", "furnace"],
    ["bun", "cookie"],
  ],
  [["furnace", "ice tea"], "tea"],
  [["egg", "flour"], "dough"],
  [["bacteria", "kvass"], "beer"],
  [["meat", "porridge"], "pilaf"],
  [["berry", "tool"], "juice"],
  [["bacteria", "berry"], "wine"],
  [["berry", "boiling water"], "jam"],
  [["berry", "kefir"], "yogurt"],
  [["egg", "sauce"], "mayonnaise"],
  [
    ["seed", "tree"],
    ["cocoa bean", "coffee bean"],
  ],
  [["manure", "tree"], "fruit"],
  [["nut", "tool"], "nut butter"],
  [["nut", "porridge"], "muesli"],
  [["honey", "nut"], "gozinaki"],
  [["bacteria", "honey"], "mead"],
  [["cookie", "honey"], "gingerbread"],
];

export const recipesByElement: RecipesByElementType = {};
recipes.forEach(([reagents, result]) => {
  if (!(reagents[0] in recipesByElement)) {
    recipesByElement[reagents[0]] = {};
  }
  const firstReagentDict = recipesByElement[reagents[0]] as {
    [key in ElementType]?: ElementType | ElementType[];
  };
  firstReagentDict[reagents[1]] = result;
  if (!(reagents[1] in recipesByElement)) {
    recipesByElement[reagents[1]] = {};
  }
  const secondReagentDict = recipesByElement[reagents[1]] as {
    [key in ElementType]?: ElementType | ElementType[];
  };
  secondReagentDict[reagents[0]] = result;
});
